import asyncio
import logging
from .sync_api import SyncConnection, SyncConnectionPool
from .async_api import AsyncConnection, AsyncConnectionPool
from .logging import db_logger

# This imports the compiled C++ engine generated by PyBind11
import _klyrodb

class Database:
    def __init__(self, path: str):
        self._path = path
        if db_logger.isEnabledFor(logging.INFO):
            db_logger.info(f"Opening database", extra={"path_len": len(path)})
        
        # Note: In a real system, you might want to open this asynchronously 
        # to prevent WAL-recovery from blocking the main thread.
        try:
            self._native = _klyrodb.open(path)
            if db_logger.isEnabledFor(logging.INFO):
                db_logger.info("Database opened successfully")
        except Exception as e:
            db_logger.error("Failed to open database", exc_info=True)
            raise

    # --- Synchronous API ---
    def connect_sync(self) -> SyncConnection:
        return SyncConnection(self._native.connect())

    def create_pool_sync(self, max_connections: int = 16) -> SyncConnectionPool:
        return SyncConnectionPool(self, max_connections)

    # --- Asynchronous API ---
    def connect_async(self) -> AsyncConnection:
        loop = asyncio.get_running_loop()
        return AsyncConnection(self._native.connect(), loop)

    def create_pool_async(self, max_connections: int = 16) -> AsyncConnectionPool:
        return AsyncConnectionPool(self, max_connections)

    def close(self):
        if db_logger.isEnabledFor(logging.INFO):
            db_logger.info("Closing database")
        self._native.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()

def open(path: str) -> Database:
    return Database(path)
